### ISSUE TITLE
Reach attributes does not work with SpartanWeaponry.

### ISSUE THREAD

**Issue by Heaveness** [bglandolt/bettercombat#23]
The Reach properties of SpartanWeaponry do not work with this mod. Even the Additional Reach from Immersive Combat's config isn't working. But the Reach from Potion effects still do. I tried this on my mod pack and a separate profile with only two mods(including prerequisite mods) with no luck. 

They all have the regular vanilla reach distance, and I tried changing "Attribute Base Reach Distance"=4.0 and it didn't seem to do anything either.

This effectively causes some of the long-range weapon types to lose value.

**Comment by bglandolt** [comment]
The Reach from Spartan Weaponry will not work, for Spartan Weaponry the attacks that are made with weapons that have reach are their own separate attacks from vanilla. Immersive Combat does something very similar to how it overwrites the vanilla attack. The Reach properties have been added in the Immersive Combat config by default so you will not need to add them yourself

However, I think there was a bug where Immersive Combat reach values were not applying correctly, which is fixed in the latest update 3/20
