### ISSUE TITLE
Fast Equip Feature Voids Items

### ISSUE THREAD

**Issue by oitsjustjose** [bglandolt/bettercombat#8]
[Full Mod List](https://gist.github.com/oitsjustjose/da96f4576e1f1e6c8af050225d135b4d)

Pressing the X key while holding a tool just makes items go away. Not anywhere to be found in the player's NBT, not a server desync, just gone.

**Comment by ANormalRaft** [comment]
To add to the initial post, for me just pressing X doesn't delete a tool, however having at least two tools in the hotbar and pressing X while hovering a slot without a tool will delete one. Having three tools like two in the inventory and one in the hotbar has similar results if I remember correctly. This also gets weird with shields in the inventory, where it will always delete something when pressing X (If I remember correctly, it also voids stuff in your inventory). I tested this behavior on a modpack with only the mod present, so this isn't caused by other mods
